
POST http://localhost:3000/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQ4M2ViMWIxOGIyODQzZjVmM2RiNyIsImlhdCI6MTcwNjkxODg5MX0.N_zDUtyTq2WvOdLU-mtR0luubP6rYBfNWhRf7l0Qzo0

{
    "title": "My Second blog",
    "banner": "https://www.google.com",
    "des": "short ex description",
    "content": {
      "blocks": [1,2]
    },
    "tags": ["tag1", "tag2"]
}



#Access token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YmQ4M2ViMWIxOGIyODQzZjVmM2RiNyIsImlhdCI6MTcwNjkxODg5MX0.N_zDUtyTq2WvOdLU-mtR0luubP6rYBfNWhRf7l0Qzo0
# POST http://localhost:3000/signup
# Content-Type: application/json

# {
#     "fullname" : "John Doe",
#     "email": "joh2@gmail.com",
#     "password": "John@123"
#   }
